//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package br.com.andreikeda.x_maps.application;

import br.com.andreikeda.x_maps.interfaces.MyPreferences_;

public final class MyApplication_
    extends MyApplication
{


    private void init_() {
        mPref = new MyPreferences_(this);
    }

    @Override
    public void onCreate() {
        init_();
        super.onCreate();
    }

}
